# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('TASK_NEW', 'New Task'), ('TASK_COMPLETED', 'Completed Task')], default='TASK_NEW', max_length=15)),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='Time when a task was first created', verbose_name='Time Created')),
                ('time_updated', models.DateTimeField(auto_now=True, help_text='Time when a task was updated', verbose_name='Time Updated')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
