# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_updated',
        ),
        migrations.AddField(
            model_name='task',
            name='time_due',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when a task was set due.', verbose_name='Time Due'),
            preserve_default=False,
        ),
    ]
