# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_task', '0003_auto_20180516_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TASK_NOT_COMPLETED', 'Not completed Task'), ('TASK_COMPLETED', 'Completed Task')], default='TASK_NOT_COMPLETED', max_length=15),
        ),
    ]
